name: PHP Composer with Cache
author: Sam Anthony

runs:
  using: "composite"
  steps:
    - name: Test
      shell: bash
      run: |
        WORKFLOW_FILE_PATH="$(echo '${{ github.workflow_ref }}' | cut -d'@' -f1)"
        echo $WORKFLOW_FILE_PATH
