name: PHP Composer with Cache
author: Sam Anthony

inputs:
  GITHUB_TOKEN:
    description: Pass in the GITHUB_TOKEN
    required: true
  composer-working-dir:
    required: true
    description: The folder containing the desired composer.json and composer.lock
  dev-option:
    description: Should dev packages be installed.
    required: true
    default: "exclude-dev"
    type: choice
    options:
      - "exclude-dev"
      - "include-dev"

runs:
  using: "composite"
  steps:
    - name: determine cache key
      shell: bash
      id: cache-key
      # Why it is important to include "This file" in the Cache Key Hash?
      #   If there is every a change to this action and the arguments passed to composer are changed, we want
      #   to include this file in the hash to ensure that the Cache Key has changed.
      # TODO
      #  THIS_FILE=${{ github.action_path }}/action.yml
      #  This file is not been used in the Cache Key Hash for the moment,
      #  ${{ github.action_path }} didn't seem compatible with kirschbaumdevelopment/laravel-test-runner:8.1

      run: |
        COMPOSER_JSON=${{ inputs.composer-working-dir }}/composer.json
        COMPOSER_LOCK=${{ inputs.composer-working-dir }}/composer.lock
        DEV_OPTION=${{ inputs.dev-option }}
        echo "Composer Working Dir: ${{ inputs.composer-working-dir }}"
        ls -la ${{ inputs.composer-working-dir }}
        CACHE_KEY=$(cat $COMPOSER_JSON $COMPOSER_LOCK | md5sum | awk '{ print $1 }')
        CACHE_KEY="$CACHE_KEY-$DEV_OPTION"
        echo "key=${CACHE_KEY}" >> "$GITHUB_OUTPUT"
        echo "Cache Key: $CACHE_KEY"

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ inputs.composer-working-dir }}/vendor
        key: ${{ steps.cache-key.outputs.key }}

    # This helps prevent the occasional "composer install" error like:
    # Failed to download xxxx/xxxxx from dist: Could not authenticate against github.com
    - name: Composer Configure Auth
      shell: bash
      run: |
        composer global config github-oauth.github.com ${{ inputs.GITHUB_TOKEN }}

    - name: Composer install
      shell: bash
      # Composer install flags
      #   --no-cache: disable the built in composer cache. The composer cache would only be installed on the temp build environment
      #     created by Github and the environment is destroyed immediately after, so this cache is useless
      #   --ignore-platform-reqs: Since composer is been ran on Github build environment, and not the real environment,
      #     we should ignore platform checks such as specific PHP Version or extensions
      #   --optimize-autoloader: This value is already set in composer.json, but no harm in ensuring it is set here
      #
      run: |
        cd ${{ inputs.composer-working-dir }}
        
        if [ "${{ inputs.dev-option }}" = "exclude-dev" ]; then
          export COMPOSER_NO_DEV=1
        else
          export COMPOSER_NO_DEV=0
        fi
        
        echo "composer no dev: $COMPOSER_NO_DEV"
        
        [ -d "vendor" ] && echo "vendor directory is present suggesting a cache hit" || composer install --no-cache --no-progress --no-interaction --ignore-platform-reqs --optimize-autoloader
        
        ls -1 vendor/

