name: PHP Composer with Cache
author: Sam Anthony

inputs:
  composer-working-dir:
    required: true
    description: The folder containing the desired composer.json and composer.lock
  dev:
    default: no
    description: Should composer dev packages be included (yes/no)
    type: choice
    options:
      - no
      - yes

runs:
  using: "composite"
  steps:
    - name: determine cache key
      shell: bash
      id: cache-key
      # Why it is important to include "This file" in the Cache Key Hash?
      #   If there is every a change to this action and the arguments passed to composer are changed, we want
      #   to include this file in the hash to ensure that the Cache Key has changed.
      run: |
        COMPOSER_JSON=${{ inputs.composer-working-dir }}/composer.json
        COMPOSER_LOCK=${{ inputs.composer-working-dir }}/composer.lock
        COMPOSER_DEV=${{ inputs.dev }}
        THIS_FILE=${{ github.action_path }}/action.yml
        CACHE_KEY=$(cat $COMPOSER_JSON $COMPOSER_LOCK $THIS_FILE | md5sum | awk '{ print $1 }')
        CACHE_KEY="$CACHE_KEY-$COMPOSER_DEV"
        echo "key=${CACHE_KEY}" >> "$GITHUB_OUTPUT"
        echo "Cache Key: $CACHE_KEY"

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ inputs.composer-working-dir }}/vendor
        key: ${{ steps.cache-key.outputs.key }}

    - name: Install dependencies
      uses: "php-actions/composer@v6"
      with:
        args: "--no-cache --ignore-platform-reqs --optimize-autoloader  "
        interaction: no # --no-interaction
        progress: no # --no-progress
        dev: ${{ inputs.dev }}
        working_dir: ${{ inputs.composer-working-dir }}
